### ISSUE TITLE
Git hash and time stamp in version information lost on "Special:Version"

### ISSUE THREAD

**Issue by kghbln** [SemanticMediaWiki/SemanticBreadcrumbLinks#19]
The latest changes to this extension caused the git hash and time stamp of the version being lost on special page "Special:Version" in the version information field. I think it will be great to get these back again. This information comes in quite nice when reporting errors.

Same for Semantic Cite, Semantic External Queries, Semantic Extra Special Properties and Semantic Interlanguage Links. See [sandbox](http://sandbox.semantic-mediawiki.org/wiki/Sp%C3%A9cial:Version).

**Comment by mwjames** [comment]
I haven't changed anything.

**Comment by mwjames** [comment]
>  "Special:Version" in the version information field. I think it will be great to get these back again.

Displaying the hash and timestamp is part of `Special:Version` [0], nothing an extension has direct influence over.

[0] https://github.com/wikimedia/mediawiki/blob/master/includes/specials/SpecialVersion.php#L261-L280

**Comment by kghbln** [comment]
This is strange since this [started](https://wikiapiary.com/w/index.php?title=Semantic_MediaWiki_-_Sandbox/Extensions&diff=2947900&oldid=2939240) with https://github.com/SemanticMediaWiki/SemanticBreadcrumbLinks/commit/b5d46b646b39662d7274583195f53d4abd58c239 which suggests to a very high correlation. Did not change MediaWiki itself.

**Comment by mwjames** [comment]
> This is strange since this started with b5d46b6 which suggests to a very high correlation. Did not change MediaWiki itself.

Here is what happens.

[0] tries to read the path and when I changed `'path' => __FILE__,` to `'path' => __DIR__,` which results in:

- `__DIR__` only contains a link to `...\extensions\SemanticBreadcrumbLinks` while
- `__FILE__` returns `...\extensions\SemanticBreadcrumbLinks\SemanticBreadcrumbLinks.php`

[0] needs a file link to determine the Git hash. So, using `__FILE__` instead of `__DIR__` should bring back your beloved git hash.

[0] https://github.com/wikimedia/mediawiki/blob/master/includes/specials/SpecialVersion.php#L716

**Comment by kghbln** [comment]
> Here is what happens.

Great, I will do a pull for this.

**Comment by mwjames** [comment]
> If this one is ok I will also to it for the other extensions mentioned.

Just fire away.

**Comment by kghbln** [comment]
@mwjames Thanks for merging!
